### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by DavideBrambilla98** [JohnnyLAmpAz/smartmag#26]
Scrivere la documentazione relativa al project plan, in particolare i seguenti punti:

- [x] Introduzione
- [x] Process model
- [x] Organizzazione
- [x] Standard, linee guida
- [x] Gestione delle attività
- [x] Rischi
- [x] Personale
- [x] Metodi e tecniche
- [x] Garanzia di qualità
- [x] Work packages
- [x] Risorse
- [x] Budget
- [x] Modifiche
- [x] Consegna

Check commit Create ProjectPlan.md
https://github.com/JohnnyLAmpAz/smartmag/commit/f66129de346820b1b1f12bf7151f4f6f4f9df14a
